### ISSUE TITLE
Why is 'sas' GID Checked

### ISSUE THREAD

**Issue by AWSmith0216** [sassoftware/virk#107]
I was running VIRK against a system where the 'sas' user and group existed, but the 'sas' group did not have GID 1001. VIRK fails with:

`"msg": "We looked for the group 'sas'. (getent group sas).\nWe found that this group already exists and has a GID of 509.\nIn your variables file, you stated that group 'sas' should have a GID of '1001'.\nTherefore, we are not making any changes. You can do one of the following\n- Review the content of the 'custom_group_list' variable to make it match your existing group(s).\n- Add  -e 'create_local_cas_and_sas_accounts=false'   to the command so that it does not verify or create accounts.\n- Add  --skip-tags user_and_group_config   to have ansible skip the entire section about users and groups.\n"
`

The deployment runs fine though, nor am I aware of any documentation that the groups have to have a specific GID. Is there some other purpose for this GID check? Isn't it sufficient that the users and groups exist, rather than having a specific ID?

**Comment by erwangranger** [comment]
Hi Adam,
You are correct that there is no particular GID required. 
What is really important is that all UIDs/GIDs for 'sas' and 'cas' have to be identical on all machines. 

This is all driven by these variables in [the main variable file](https://github.com/sassoftware/virk/blob/viya-3.4/playbooks/pre-install-playbook/roles/virk.preinstall/defaults/main.yml#L18L23) . 
In order to make sure it would be consistent, we had to pick a value. (1001, 1002). 

But, if the users existed with alternative values, we did not want to change the UID or GID to *our* desired values as this would have bad consequences.

At the same time, just because the users exist is not quite good enough, because your UID/GIDs may not be identical on all machines. 

If you create a custom file for your variable overrides (say virk_override.yml) and include the right info in there to match with your environment , you can call that file with the `-e "@virk_override.yml"` syntax. 
In that file, you'd put: 

```yml
custom_group_list:
  - { group: "{{sas_group}}",       gid: 509 }

custom_user_list:
  - { name: "{{sas_user}}" , uid: 1001 ,  group: "{{sas_group}}",  groups: "{{sas_group}}"}
  - { name: "{{cas_user}}" , uid: 1002 ,  group: "{{sas_group}}",  groups: "{{sas_group}}"}
```

Note that you probably want to update the UID for sas and cas to match your environment, or you'll get a failure with the accounts too. 

It was a design choice to try to exit with a long-winded error message instead of potentially modifying existing users/groups. 

I hope this helps.
