### ISSUE TITLE
For CAS Resource Management in Viya 3.4, some additional packages are required

### ISSUE THREAD

**Issue by erwangranger** [sassoftware/virk#52]
From the draft documentation for Viya 3.4: 
> (Optional) Additional Requirements for CAS Resource Management
> The CAS resource policies that you can configure on CAS servers include an optional method for managing hardware resources. To support CAS resource policies, verify that your environment meets the following requirements:
> - The libcgroup and libcgroup-tools Linux packages are installed.
These packages are typically included with the operating system.
> - The cgconfig service has been started.
This service is installed with the libcgroup package, but on some varieties of Linux, it is not automatically started.
> - The cgroups file system has been mounted.

Can we add these checks and packages to the 3.4 branch of the VIRK pre-req playbooks?

**Comment by thpang** [comment]
Would these be in the ‘nice to have package’ section? Seems like extra not really needed but would be helpful if they were there.

**Comment by erwangranger** [comment]
Although these features of resource management are technically optional, I'd say that this should NOT be in the "nice to have" section. (in my mind, nice-to-have are for things that can be handy, but not required for the software to function). 
In this case, if you don't have those packages and services, you will not be able to use the resource management features. 
So I'd rather make it a "must-have". 

(also, keep in mind, it's not just a few packages, but also to ensure that a service is running).

**Comment by erwangranger** [comment]
So far, our approach has been to be safe, and to apply pre-reqs identically to all machines. 
I know that we end up doing "too much" on some machines, but I find the trade off worth it. 

If someone wants to tailor things more precisely, they can edit the playbook and do multiple runs for multiple machines with multiple values overrides. 
Like: 
```yaml
- hosts: host1,host2
  become: yes
  become_user: root
  vars:
    min_mem_mb: 10000
    min_cores_num: 1
  roles:
   - virk.preinstall

- hosts: host3,host4
  become: yes
  become_user: root
  vars:
    min_mem_mb: 90000
    min_cores_num: 10
  roles:
   - virk.preinstall
```
